### ISSUE TITLE
为什么使用self.render去到浏览器变成了下载

### ISSUE THREAD

**Issue by yincangshiwei** [devsapp/start-web-framework#103]
如题，我代码里面使用self.render('index.html')跳转页面，去到浏览器会变成了下载。访问云函数的时候。。

**Comment by heimanba** [comment]
需要自定义域名（系统域名默认行为是下载），可以使用curl测试下是否能够正确返回

**Comment by heimanba** [comment]
> 

建议绑定自定义域名解决
