### ISSUE TITLE
hapi 应用存在问题

### ISSUE THREAD

**Issue by wss-git** [devsapp/start-web-framework#54]
s init start-hapi -d start-hapi  部署之后访问失败：原因 custom 默认是 node 版本是 10  我测试是 12 以上可以是启动的

s init hapi-app -d hapi-app     部署之后访问没有样式

**Comment by heimanba** [comment]
样式问题已经修复

**Comment by heimanba** [comment]
s init start-hapi -d start-hapi 也修复成功
