### ISSUE TITLE
部署后报Function instance exited unexpectedly

### ISSUE THREAD

**Issue by quanzaiyu** [devsapp/start-web-framework#72]
通过 `s deploy` 部署到阿里云fc后报错：

```
Function instance exited unexpectedly(code 1, message:operation not permitted) with start command 'java org.springframework.boot.loader.JarLauncher'.\nLogs:Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
```

![image](https://user-images.githubusercontent.com/13745132/206399862-c9fdd4cd-d427-4904-b920-b698980e8609.png)

部署链接：http://springboot.spring-boot-service.1713938831368082.cn-shenzhen.fc.devsapp.net/

**Comment by heimanba** [comment]
麻烦执行下 s clean --all再看下效果

**Comment by quanzaiyu** [comment]
> 麻烦执行下 s clean --all再看下效果

谢谢，执行后重新部署，已成功：
![image](https://user-images.githubusercontent.com/13745132/206609617-902cdf3f-071e-4ac4-80c8-a4eac44327ec.png)
